<a href="https://colab.research.google.com/github/NodanKumar/BreastCancerPrediction/blob/main/Breast_Cancer_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Breast cancer detection with logistic regression**


In [ ]:
#import libraries
import numpy as np
import sklearn

In [ ]:
# getting the dataset
breast_cancer = sklearn.datasets.load_breast_cancer()
print(breast_cancer)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [ ]:
x = breast_cancer.data
y = breast_cancer.target
print(x)
print(y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [ ]:
print(x.shape, y.shape)

(569, 30) (569,)


**import data to the pandas data frame**


In [ ]:
import pandas as pd


In [ ]:
data = pd.DataFrame(breast_cancer.data, columns=breast_cancer.feature_names)
print(data)


     mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]


In [ ]:
data["class"] = breast_cancer.target
print(data["class"])

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: class, Length: 569, dtype: int64


In [ ]:
data.head()

mean radius  mean texture  ...  worst fractal dimension  class
0        17.99         10.38  ...                  0.11890      0
1        20.57         17.77  ...                  0.08902      0
2        19.69         21.25  ...                  0.08758      0
3        11.42         20.38  ...                  0.17300      0
4        20.29         14.34  ...                  0.07678      0

[5 rows x 31 columns]

In [ ]:
# to understand basics our data
data.describe()

mean radius  mean texture  ...  worst fractal dimension       class
count   569.000000    569.000000  ...               569.000000  569.000000
mean     14.127292     19.289649  ...                 0.083946    0.627417
std       3.524049      4.301036  ...                 0.018061    0.483918
min       6.981000      9.710000  ...                 0.055040    0.000000
25%      11.700000     16.170000  ...                 0.071460    0.000000
50%      13.370000     18.840000  ...                 0.080040    1.000000
75%      15.780000     21.800000  ...                 0.092080    1.000000
max      28.110000     39.280000  ...                 0.207500    1.000000

[8 rows x 31 columns]

In [ ]:
# to know how many samples are present for melignant and benign
print(data["class"].value_counts())

1    357
0    212
Name: class, dtype: int64


In [ ]:
print(breast_cancer.target_names)

['malignant' 'benign']


In [ ]:
data.groupby("class").mean()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
class                             ...                                         
0        17.462830     21.604906  ...        0.323468                 0.091530
1        12.146524     17.914762  ...        0.270246                 0.079442

[2 rows x 30 columns]

**train test and split**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [ ]:
print(y.shape, y_train.shape, y_test.shape)

(569,) (426,) (143,)


**To adjust training and test data we use test size**


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1)

In [ ]:
print(y.shape, y_train.shape, y_test.shape)

(569,) (512,) (57,)


In [ ]:
print(y.mean(), y_train.mean(), y_test.mean())

0.6274165202108963 0.615234375 0.7368421052631579


**stratify --->for correct distribution of data**

In [ ]:
# make sure to adjust mean with a little difference
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, stratify=y)
print(y.mean(), y_train.mean(), y_test.mean())

0.6274165202108963 0.626953125 0.631578947368421


In [ ]:
# Random state-->specific split of data..each value of random state splits the data differently
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=1)

In [ ]:
print(x.mean(), x_train.mean(), x_test.mean())

61.890712339519624 61.8522373819401 62.23631195847954


**Logistic Regresion(best for binary classificatio)**
import logistic regression from sklean

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
#loading the logistic regression model to the variable called classifier
classifier = LogisticRegression()

In [ ]:
#training the model on taining data
classifier.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

**Evaluation of the model**

In [ ]:
from sklearn.metrics import accuracy_score
prediction_on_training_data = classifier.predict(x_train)
accuracy = accuracy_score(y_train, prediction_on_training_data)
print("accuracy_on_training_data: ", accuracy)


accuracy_on_training_data:  0.943359375


In [ ]:
prediction_on_test_data = classifier.predict(x_test)
accuracy = accuracy_score(y_test, prediction_on_test_data)
print("accuracy_on_test_data :", accuracy)

accuracy_on_test_data : 1.0


 **Detecting whether the patient belongs to melignant or benign state**

In [ ]:
input_data = (12.31,16.52,79.19,470.9,0.09172,0.06829,0.03372,0.02272,0.172,0.05914,0.2505,1.025,1.74,19.68,0.004854,0.01819,0.01826,0.007965,0.01386,0.002304,14.11,23.21,89.71,611.1,0.1176,0.1843,0.1703,0.0866,0.2618,0.07609)


**Change input data to numpy array to make prediction**

In [ ]:
input_data_as_numpy_array = np.array(input_data)
print(input_data)
print(input_data_as_numpy_array)

(12.31, 16.52, 79.19, 470.9, 0.09172, 0.06829, 0.03372, 0.02272, 0.172, 0.05914, 0.2505, 1.025, 1.74, 19.68, 0.004854, 0.01819, 0.01826, 0.007965, 0.01386, 0.002304, 14.11, 23.21, 89.71, 611.1, 0.1176, 0.1843, 0.1703, 0.0866, 0.2618, 0.07609)
[1.231e+01 1.652e+01 7.919e+01 4.709e+02 9.172e-02 6.829e-02 3.372e-02
 2.272e-02 1.720e-01 5.914e-02 2.505e-01 1.025e+00 1.740e+00 1.968e+01
 4.854e-03 1.819e-02 1.826e-02 7.965e-03 1.386e-02 2.304e-03 1.411e+01
 2.321e+01 8.971e+01 6.111e+02 1.176e-01 1.843e-01 1.703e-01 8.660e-02
 2.618e-01 7.609e-02]


In [ ]:
input_data_reshaped = input_data_as_numpy_array.reshape(1, -1)
print(input_data_reshaped)

# prediction
prediction = classifier.predict(input_data_reshaped)

[[1.231e+01 1.652e+01 7.919e+01 4.709e+02 9.172e-02 6.829e-02 3.372e-02
  2.272e-02 1.720e-01 5.914e-02 2.505e-01 1.025e+00 1.740e+00 1.968e+01
  4.854e-03 1.819e-02 1.826e-02 7.965e-03 1.386e-02 2.304e-03 1.411e+01
  2.321e+01 8.971e+01 6.111e+02 1.176e-01 1.843e-01 1.703e-01 8.660e-02
  2.618e-01 7.609e-02]]


In [ ]:
if prediction[0]==0:
  print("patient is at melignat state")
else:
  print("patient is at benign state")  

patient is at benign state
